# coding: utf-8

"""
    Edge Function API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from edgefunctions.models.put_edge_function_request import PutEdgeFunctionRequest  # noqa: E501

class TestPutEdgeFunctionRequest(unittest.TestCase):
    """PutEdgeFunctionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutEdgeFunctionRequest:
        """Test PutEdgeFunctionRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutEdgeFunctionRequest`
        """
        model = PutEdgeFunctionRequest()  # noqa: E501
        if include_optional:
            return PutEdgeFunctionRequest(
                name = '',
                code = '',
                json_args = None,
                active = True,
                initiator_type = 'edge_application',
                language = '',
                is_proprietary_code = True
            )
        else:
            return PutEdgeFunctionRequest(
        )
        """

    def testPutEdgeFunctionRequest(self):
        """Test PutEdgeFunctionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
