# coding: utf-8

"""
    Intelligent DNS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, conlist
from idns.models.zone import Zone

class PostOrPutZoneResponse(BaseModel):
    """
    Object returned by create or update zone  # noqa: E501
    """
    schema_version: Optional[StrictInt] = Field(None, description="The schema version")
    results: Optional[conlist(Zone)] = Field(None, description="The created hosted zone")
    __properties = ["schema_version", "results"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PostOrPutZoneResponse:
        """Create an instance of PostOrPutZoneResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in results (list)
        _items = []
        if self.results:
            for _item in self.results:
                if _item:
                    _items.append(_item.to_dict())
            _dict['results'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PostOrPutZoneResponse:
        """Create an instance of PostOrPutZoneResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PostOrPutZoneResponse.parse_obj(obj)

        _obj = PostOrPutZoneResponse.parse_obj({
            "schema_version": obj.get("schema_version"),
            "results": [Zone.from_dict(_item) for _item in obj.get("results")] if obj.get("results") is not None else None
        })
        return _obj


