# coding: utf-8

"""


    Generated by: https://openapi-generator.tech
"""

import unittest
from unittest.mock import patch

import urllib3

import digital_certificates
from digital_certificates.paths.digital_certificates_csr import post  # noqa: E501
from digital_certificates import configuration, schemas, api_client

from .. import ApiTestMixin


class TestDigitalCertificatesCsr(ApiTestMixin, unittest.TestCase):
    """
    DigitalCertificatesCsr unit test stubs
        Create an encrypted Certificate Request with Azion, which can then be sent for signing to a CA  # noqa: E501
    """
    _configuration = configuration.Configuration()

    def setUp(self):
        used_api_client = api_client.ApiClient(configuration=self._configuration)
        self.api = post.ApiForpost(api_client=used_api_client)  # noqa: E501

    def tearDown(self):
        pass

    response_status = 201






if __name__ == '__main__':
    unittest.main()
