# coding: utf-8

"""
    Intelligent DNS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from idns.models.get_zones_response import GetZonesResponse  # noqa: E501

class TestGetZonesResponse(unittest.TestCase):
    """GetZonesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetZonesResponse:
        """Test GetZonesResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetZonesResponse`
        """
        model = GetZonesResponse()  # noqa: E501
        if include_optional:
            return GetZonesResponse(
                schema_version = 56,
                count = 56,
                total_pages = 56,
                links = {"next":"next","previous":"previous"},
                results = [
                    {"is_active":true,"nameservers":["nameservers","nameservers"],"domain":"domain","name":"name","soa_ttl":7,"refresh":9,"nx_ttl":2,"id":5,"expiry":3,"retry":5}
                    ]
            )
        else:
            return GetZonesResponse(
        )
        """

    def testGetZonesResponse(self):
        """Test GetZonesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
