# coding: utf-8

"""
    Intelligent DNS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from idns.models.get_or_patch_dns_sec_response import GetOrPatchDnsSecResponse  # noqa: E501

class TestGetOrPatchDnsSecResponse(unittest.TestCase):
    """GetOrPatchDnsSecResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOrPatchDnsSecResponse:
        """Test GetOrPatchDnsSecResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOrPatchDnsSecResponse`
        """
        model = GetOrPatchDnsSecResponse()  # noqa: E501
        if include_optional:
            return GetOrPatchDnsSecResponse(
                schema_version = 56,
                results = {"is_enabled":true,"delegation_signer":{"key_tag":9607,"digest_type":{"id":6,"slug":"slug"},"algorithm_type":{"id":6,"slug":"slug"},"digest":"digest"},"status":"unconfigured"}
            )
        else:
            return GetOrPatchDnsSecResponse(
        )
        """

    def testGetOrPatchDnsSecResponse(self):
        """Test GetOrPatchDnsSecResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
