# coding: utf-8

"""
    Intelligent DNS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from idns.models.post_or_put_zone_response import PostOrPutZoneResponse  # noqa: E501

class TestPostOrPutZoneResponse(unittest.TestCase):
    """PostOrPutZoneResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostOrPutZoneResponse:
        """Test PostOrPutZoneResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostOrPutZoneResponse`
        """
        model = PostOrPutZoneResponse()  # noqa: E501
        if include_optional:
            return PostOrPutZoneResponse(
                schema_version = 56,
                results = [
                    {"is_active":true,"nameservers":["nameservers","nameservers"],"domain":"domain","name":"name","soa_ttl":7,"refresh":9,"nx_ttl":2,"id":5,"expiry":3,"retry":5}
                    ]
            )
        else:
            return PostOrPutZoneResponse(
        )
        """

    def testPostOrPutZoneResponse(self):
        """Test PostOrPutZoneResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
