# coding: utf-8

"""
    Web Application Firewall API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from waf.models.waf_list200 import WAFList200  # noqa: E501

class TestWAFList200(unittest.TestCase):
    """WAFList200 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WAFList200:
        """Test WAFList200
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WAFList200`
        """
        model = WAFList200()  # noqa: E501
        if include_optional:
            return WAFList200(
                count = 56,
                total_pages = 56,
                links = {"id":28852,"name":"Waf Name","mode":"counting","active":true,"sql_injection":true,"sql_injection_sensitivity":"medium","remote_file_inclusion":true,"remote_file_inclusion_sensitivity":"medium","directory_traversal":true,"directory_traversal_sensitivity":"medium","cross_site_scripting":true,"cross_site_scripting_sensitivity":"medium","evading_tricks":true,"evading_tricks_sensitivity":"medium","file_upload":true,"file_upload_sensitivity":"medium","unwanted_access":true,"unwanted_access_sensitivity":"medium","identified_attack":true,"identified_attack_sensitivity":"medium","bypass_addresses":[]},
                schema_version = 3
            )
        else:
            return WAFList200(
        )
        """

    def testWAFList200(self):
        """Test WAFList200"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
