# coding: utf-8

"""
    Web Application Firewall API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from waf.models.waf_events404 import WAFEvents404  # noqa: E501

class TestWAFEvents404(unittest.TestCase):
    """WAFEvents404 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WAFEvents404:
        """Test WAFEvents404
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WAFEvents404`
        """
        model = WAFEvents404()  # noqa: E501
        if include_optional:
            return WAFEvents404(
                errors = [
                    {"message":"Network List not found","error":"not_found"}
                    ],
                schema_version = 3
            )
        else:
            return WAFEvents404(
        )
        """

    def testWAFEvents404(self):
        """Test WAFEvents404"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
