# coding: utf-8

"""
    Data Streaming - OpenAPI

    The Data Streaming API allows you to manage your existing data streamings and templates. Data Streaming allows you to feed your stream processing, SIEM, and big data platforms with the event logs from your applications on Azion in real time. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import data_streaming
from data_streaming.api.data_streaming_templates_api import DataStreamingTemplatesApi  # noqa: E501
from data_streaming.rest import ApiException


class TestDataStreamingTemplatesApi(unittest.TestCase):
    """DataStreamingTemplatesApi unit test stubs"""

    def setUp(self):
        self.api = data_streaming.api.data_streaming_templates_api.DataStreamingTemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_data_straming_template_by_id(self):
        """Test case for get_data_straming_template_by_id

        Get an global Template info by template ID  # noqa: E501
        """
        pass

    def test_list_data_streaming_templates(self):
        """Test case for list_data_streaming_templates

        List all global Templates that can be used on Data Streaming operations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
