# coding: utf-8

"""
    Edge Application API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import edgeapplications
from edgeapplications.models.create_application_request import CreateApplicationRequest  # noqa: E501
from edgeapplications.rest import ApiException

class TestCreateApplicationRequest(unittest.TestCase):
    """CreateApplicationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateApplicationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateApplicationRequest`
        """
        model = edgeapplications.models.create_application_request.CreateApplicationRequest()  # noqa: E501
        if include_optional :
            return CreateApplicationRequest(
                name = '', 
                application_acceleration = True, 
                delivery_protocol = '', 
                origin_type = '', 
                address = '', 
                minimum_tls_version = '', 
                origin_protocol_policy = '', 
                host_header = '', 
                browser_cache_settings = '', 
                cdn_cache_settings = '', 
                browser_cache_settings_maximum_ttl = 56, 
                cdn_cache_settings_maximum_ttl = 56, 
                debug_rules = True, 
                supported_ciphers = '', 
                http_port = None, 
                https_port = None, 
                l2_caching = True, 
                http3 = True, 
                websocket = True
            )
        else :
            return CreateApplicationRequest(
                name = '',
        )
        """

    def testCreateApplicationRequest(self):
        """Test CreateApplicationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
