# coding: utf-8

"""
    Edge Application API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import edgeapplications
from edgeapplications.api.edge_applications_origins_api import EdgeApplicationsOriginsApi  # noqa: E501
from edgeapplications.rest import ApiException


class TestEdgeApplicationsOriginsApi(unittest.TestCase):
    """EdgeApplicationsOriginsApi unit test stubs"""

    def setUp(self):
        self.api = edgeapplications.api.edge_applications_origins_api.EdgeApplicationsOriginsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_edge_applications_edge_application_id_origins_get(self):
        """Test case for edge_applications_edge_application_id_origins_get

        /edge_applications/{edge_application_id}/origins  # noqa: E501
        """
        pass

    def test_edge_applications_edge_application_id_origins_origin_key_delete(self):
        """Test case for edge_applications_edge_application_id_origins_origin_key_delete

        /edge_applications/{edge_application_id}/origins/{origin_id}  # noqa: E501
        """
        pass

    def test_edge_applications_edge_application_id_origins_origin_key_get(self):
        """Test case for edge_applications_edge_application_id_origins_origin_key_get

        /edge_applications/{edge_application_id}/origins/{origin_key}  # noqa: E501
        """
        pass

    def test_edge_applications_edge_application_id_origins_origin_key_patch(self):
        """Test case for edge_applications_edge_application_id_origins_origin_key_patch

        /edge_applications/:edge_application_id:/origins/:origin_id:  # noqa: E501
        """
        pass

    def test_edge_applications_edge_application_id_origins_origin_key_put(self):
        """Test case for edge_applications_edge_application_id_origins_origin_key_put

        /edge_applications/{edge_application_id}/origins/{origin_id}  # noqa: E501
        """
        pass

    def test_edge_applications_edge_application_id_origins_post(self):
        """Test case for edge_applications_edge_application_id_origins_post

        /edge_applications/{edge_application_id}/origins  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
