# coding: utf-8

"""
    Edge Application API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import edgeapplications
from edgeapplications.models.create_rules_engine_request import CreateRulesEngineRequest  # noqa: E501
from edgeapplications.rest import ApiException

class TestCreateRulesEngineRequest(unittest.TestCase):
    """CreateRulesEngineRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateRulesEngineRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateRulesEngineRequest`
        """
        model = edgeapplications.models.create_rules_engine_request.CreateRulesEngineRequest()  # noqa: E501
        if include_optional :
            return CreateRulesEngineRequest(
                name = '', 
                description = '', 
                criteria = [
                    [
                        {"conditional":"conditional","variable":"variable","input_value":"input_value","operator":"operator"}
                        ]
                    ], 
                behaviors = [
                    {"name":"name","target":"target"}
                    ]
            )
        else :
            return CreateRulesEngineRequest(
                name = '',
                criteria = [
                    [
                        {"conditional":"conditional","variable":"variable","input_value":"input_value","operator":"operator"}
                        ]
                    ],
                behaviors = [
                    {"name":"name","target":"target"}
                    ],
        )
        """

    def testCreateRulesEngineRequest(self):
        """Test CreateRulesEngineRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
