# coding: utf-8

"""
    Edge Application API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import edgeapplications
from edgeapplications.models.get_applications_response import GetApplicationsResponse  # noqa: E501
from edgeapplications.rest import ApiException

class TestGetApplicationsResponse(unittest.TestCase):
    """GetApplicationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GetApplicationsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetApplicationsResponse`
        """
        model = edgeapplications.models.get_applications_response.GetApplicationsResponse()  # noqa: E501
        if include_optional :
            return GetApplicationsResponse(
                count = 56, 
                total_pages = 56, 
                schema_version = 56, 
                links = {"next":"next","previous":"previous"}, 
                results = [
                    edgeapplications.models.applications_results.ApplicationsResults(
                        id = 56, 
                        name = '', 
                        debug_rules = True, 
                        last_editor = '', 
                        last_modified = '', 
                        active = True, 
                        origins = [
                            edgeapplications.models.application_origins.ApplicationOrigins(
                                name = '', 
                                origin_type = '', 
                                origin_id = '', )
                            ], )
                    ], 
                next = '', 
                previous = ''
            )
        else :
            return GetApplicationsResponse(
                count = 56,
                total_pages = 56,
                schema_version = 56,
                links = {"next":"next","previous":"previous"},
                results = [
                    edgeapplications.models.applications_results.ApplicationsResults(
                        id = 56, 
                        name = '', 
                        debug_rules = True, 
                        last_editor = '', 
                        last_modified = '', 
                        active = True, 
                        origins = [
                            edgeapplications.models.application_origins.ApplicationOrigins(
                                name = '', 
                                origin_type = '', 
                                origin_id = '', )
                            ], )
                    ],
        )
        """

    def testGetApplicationsResponse(self):
        """Test GetApplicationsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
