# coding: utf-8

"""
    Edge Firewall API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from edgefirewall.models.update_edge_firewall_request import UpdateEdgeFirewallRequest  # noqa: E501

class TestUpdateEdgeFirewallRequest(unittest.TestCase):
    """UpdateEdgeFirewallRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateEdgeFirewallRequest:
        """Test UpdateEdgeFirewallRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateEdgeFirewallRequest`
        """
        model = UpdateEdgeFirewallRequest()  # noqa: E501
        if include_optional:
            return UpdateEdgeFirewallRequest(
                name = '',
                domains = [
                    56
                    ],
                is_active = True,
                edge_functions_enabled = True,
                network_protection_enabled = True,
                waf_enabled = True
            )
        else:
            return UpdateEdgeFirewallRequest(
        )
        """

    def testUpdateEdgeFirewallRequest(self):
        """Test UpdateEdgeFirewallRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
