# coding: utf-8

"""
    Edge Firewall API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from edgefirewall.models.set_waf_rule_set_and_waf_mode_behavior import SetWAFRuleSetAndWafModeBehavior  # noqa: E501

class TestSetWAFRuleSetAndWafModeBehavior(unittest.TestCase):
    """SetWAFRuleSetAndWafModeBehavior unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetWAFRuleSetAndWafModeBehavior:
        """Test SetWAFRuleSetAndWafModeBehavior
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetWAFRuleSetAndWafModeBehavior`
        """
        model = SetWAFRuleSetAndWafModeBehavior()  # noqa: E501
        if include_optional:
            return SetWAFRuleSetAndWafModeBehavior(
                name = 'set_waf_ruleset_and_waf_mode',
                argument = {"set_waf_ruleset_and_waf_mode":1,"waf_mode":"blocking"}
            )
        else:
            return SetWAFRuleSetAndWafModeBehavior(
        )
        """

    def testSetWAFRuleSetAndWafModeBehavior(self):
        """Test SetWAFRuleSetAndWafModeBehavior"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
