# coding: utf-8

"""
    Edge Firewall API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from edgefirewall.models.rule_set_response import RuleSetResponse  # noqa: E501

class TestRuleSetResponse(unittest.TestCase):
    """RuleSetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RuleSetResponse:
        """Test RuleSetResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RuleSetResponse`
        """
        model = RuleSetResponse()  # noqa: E501
        if include_optional:
            return RuleSetResponse(
                name = '',
                is_active = True,
                behaviors = [
                    edgefirewall.models.behaviors.Behaviors(
                        name = 'deny', 
                        target = '', )
                    ],
                criteria = [
                    [
                        edgefirewall.models.ssl_verification_status_criteria.SSLVerificationStatusCriteria(
                            variable = 'header_accept', 
                            operator = 'is_equal', 
                            conditional = 'if', 
                            input_value = 'SUCCESS', )
                        ]
                    ],
                last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_editor = '',
                id = 1,
                order = 1
            )
        else:
            return RuleSetResponse(
        )
        """

    def testRuleSetResponse(self):
        """Test RuleSetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
