# coding: utf-8

"""
    Edge Firewall API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from edgefirewall.models.set_waf_rule_set_behavior import SetWAFRuleSetBehavior  # noqa: E501

class TestSetWAFRuleSetBehavior(unittest.TestCase):
    """SetWAFRuleSetBehavior unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetWAFRuleSetBehavior:
        """Test SetWAFRuleSetBehavior
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetWAFRuleSetBehavior`
        """
        model = SetWAFRuleSetBehavior()  # noqa: E501
        if include_optional:
            return SetWAFRuleSetBehavior(
                name = 'set_waf_ruleset',
                argument = {"waf_id":1,"mode":"blocking"}
            )
        else:
            return SetWAFRuleSetBehavior(
        )
        """

    def testSetWAFRuleSetBehavior(self):
        """Test SetWAFRuleSetBehavior"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
