# coding: utf-8

"""
    Edge Firewall API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from edgefirewall.models.edge_firewall import EdgeFirewall  # noqa: E501

class TestEdgeFirewall(unittest.TestCase):
    """EdgeFirewall unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EdgeFirewall:
        """Test EdgeFirewall
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EdgeFirewall`
        """
        model = EdgeFirewall()  # noqa: E501
        if include_optional:
            return EdgeFirewall(
                id = 56,
                name = '',
                is_active = True,
                last_editor = '',
                last_modified = '',
                edge_functions_enabled = True,
                network_protection_enabled = True,
                waf_enabled = True,
                debug_rules = True,
                domains = [
                    56
                    ]
            )
        else:
            return EdgeFirewall(
        )
        """

    def testEdgeFirewall(self):
        """Test EdgeFirewall"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
