# coding: utf-8

"""
    Network Lists API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from networklist.models.network_list_response_entry import NetworkListResponseEntry  # noqa: E501

class TestNetworkListResponseEntry(unittest.TestCase):
    """NetworkListResponseEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NetworkListResponseEntry:
        """Test NetworkListResponseEntry
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NetworkListResponseEntry`
        """
        model = NetworkListResponseEntry()  # noqa: E501
        if include_optional:
            return NetworkListResponseEntry(
                id = 1614,
                last_editor = 'Azion',
                last_modified = '2023-08-10T05:00:07.893747Z',
                list_type = 'ip_cidr',
                name = 'Network List created using the API',
                items_values = ["192.168.0.1"]
            )
        else:
            return NetworkListResponseEntry(
        )
        """

    def testNetworkListResponseEntry(self):
        """Test NetworkListResponseEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
