# coding: utf-8

# flake8: noqa

"""
    Intelligent DNS API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from idns.api_client import ApiClient

# import Configuration
from idns.configuration import Configuration

# import exceptions
from idns.exceptions import OpenApiException
from idns.exceptions import ApiAttributeError
from idns.exceptions import ApiTypeError
from idns.exceptions import ApiValueError
from idns.exceptions import ApiKeyError
from idns.exceptions import ApiException
