# coding: utf-8

"""
    Data Streaming - OpenAPI

    The Data Streaming API allows you to manage your existing data streamings and templates. Data Streaming allows you to feed your stream processing, SIEM, and big data platforms with the event logs from your applications on Azion in real time. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, conlist
from data_streaming.models.post_data_streaming_response import PostDataStreamingResponse

class CreateDataStreamingResponse(BaseModel):
    """
    CreateDataStreamingResponse
    """
    results: Optional[conlist(PostDataStreamingResponse)] = None
    schema_version: Optional[Union[StrictFloat, StrictInt]] = None
    __properties = ["results", "schema_version"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateDataStreamingResponse:
        """Create an instance of CreateDataStreamingResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in results (list)
        _items = []
        if self.results:
            for _item in self.results:
                if _item:
                    _items.append(_item.to_dict())
            _dict['results'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateDataStreamingResponse:
        """Create an instance of CreateDataStreamingResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateDataStreamingResponse.parse_obj(obj)

        _obj = CreateDataStreamingResponse.parse_obj({
            "results": [PostDataStreamingResponse.from_dict(_item) for _item in obj.get("results")] if obj.get("results") is not None else None,
            "schema_version": obj.get("schema_version")
        })
        return _obj


