# coding: utf-8

"""
    Data Streaming - OpenAPI

    The Data Streaming API allows you to manage your existing data streamings and templates. Data Streaming allows you to feed your stream processing, SIEM, and big data platforms with the event logs from your applications on Azion in real time. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt, StrictStr
from data_streaming.models.data_streaming_endpoint_type_standard_headers_example import DataStreamingEndpointTypeStandardHeadersExample

class DataStreamingEndpointTypeStandard(BaseModel):
    """
    DataStreamingEndpointTypeStandard
    """
    endpoint_type: Optional[StrictStr] = None
    url: Optional[StrictStr] = None
    log_line_separator: Optional[StrictStr] = None
    payload_format: Optional[StrictStr] = None
    max_size: Optional[StrictInt] = None
    headers: Optional[DataStreamingEndpointTypeStandardHeadersExample] = None
    __properties = ["endpoint_type", "url", "log_line_separator", "payload_format", "max_size", "headers"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DataStreamingEndpointTypeStandard:
        """Create an instance of DataStreamingEndpointTypeStandard from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of headers
        if self.headers:
            _dict['headers'] = self.headers.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DataStreamingEndpointTypeStandard:
        """Create an instance of DataStreamingEndpointTypeStandard from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DataStreamingEndpointTypeStandard.parse_obj(obj)

        _obj = DataStreamingEndpointTypeStandard.parse_obj({
            "endpoint_type": obj.get("endpoint_type"),
            "url": obj.get("url"),
            "log_line_separator": obj.get("log_line_separator"),
            "payload_format": obj.get("payload_format"),
            "max_size": obj.get("max_size"),
            "headers": DataStreamingEndpointTypeStandardHeadersExample.from_dict(obj.get("headers")) if obj.get("headers") is not None else None
        })
        return _obj


