# coding: utf-8

"""
    Services API

    Azion Services  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import services
from services.model.update_service_request import UpdateServiceRequest
from services import configuration


class TestUpdateServiceRequest(unittest.TestCase):
    """UpdateServiceRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
