# coding: utf-8

"""
    Credentials API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

from credentials.paths.credentials.post import CreateCredential
from credentials.paths.credentials_credential_id.delete import DeleteCredential
from credentials.paths.credentials.get import FindAll
from credentials.paths.credentials_credential_id.get import LoadCredential
from credentials.paths.credentials_credential_id.patch import UpdateCredential


class DefaultApi(
    CreateCredential,
    DeleteCredential,
    FindAll,
    LoadCredential,
    UpdateCredential,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
