# coding: utf-8

# flake8: noqa
"""
    Edge Firewall API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from edgefirewall.models.behaviors import Behaviors
from edgefirewall.models.conditionals import Conditionals
from edgefirewall.models.create_edge_firewall_request import CreateEdgeFirewallRequest
from edgefirewall.models.create_rule_set_request import CreateRuleSetRequest
from edgefirewall.models.edge_firewall import EdgeFirewall
from edgefirewall.models.edge_firewall_response import EdgeFirewallResponse
from edgefirewall.models.links import Links
from edgefirewall.models.list_edge_firewall_response import ListEdgeFirewallResponse
from edgefirewall.models.null_argument_behavior import NullArgumentBehavior
from edgefirewall.models.rule_set_response import RuleSetResponse
from edgefirewall.models.rule_set_response_all import RuleSetResponseAll
from edgefirewall.models.rule_set_result import RuleSetResult
from edgefirewall.models.rule_set_result_all import RuleSetResultAll
from edgefirewall.models.rule_set_result_results import RuleSetResultResults
from edgefirewall.models.ssl_verification_status_arguments import SSLVerificationStatusArguments
from edgefirewall.models.ssl_verification_status_criteria import SSLVerificationStatusCriteria
from edgefirewall.models.ssl_verification_status_operators import SSLVerificationStatusOperators
from edgefirewall.models.set_custom_response import SetCustomResponse
from edgefirewall.models.set_custom_response_argument import SetCustomResponseArgument
from edgefirewall.models.set_custom_response_argument_status_code import SetCustomResponseArgumentStatusCode
from edgefirewall.models.set_rate_limit_behavior import SetRateLimitBehavior
from edgefirewall.models.set_rate_limit_behavior_argument import SetRateLimitBehaviorArgument
from edgefirewall.models.set_rate_limit_behavior_argument_average_rate_limit import SetRateLimitBehaviorArgumentAverageRateLimit
from edgefirewall.models.set_waf_rule_set_and_waf_mode_behavior import SetWAFRuleSetAndWafModeBehavior
from edgefirewall.models.set_waf_rule_set_and_waf_mode_behavior_argument import SetWAFRuleSetAndWafModeBehaviorArgument
from edgefirewall.models.set_waf_rule_set_behavior import SetWAFRuleSetBehavior
from edgefirewall.models.set_waf_rule_set_behavior_argument import SetWAFRuleSetBehaviorArgument
from edgefirewall.models.simple_argument_behavior import SimpleArgumentBehavior
from edgefirewall.models.simple_argument_behavior_argument import SimpleArgumentBehaviorArgument
from edgefirewall.models.update_edge_firewall_request import UpdateEdgeFirewallRequest
from edgefirewall.models.variables import Variables
