# coding: utf-8

"""
    Edge Firewall API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, StrictBool, StrictInt, StrictStr, conlist

class EdgeFirewall(BaseModel):
    """
    EdgeFirewall
    """
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    is_active: Optional[StrictBool] = None
    last_editor: Optional[StrictStr] = None
    last_modified: Optional[StrictStr] = None
    edge_functions_enabled: Optional[StrictBool] = None
    network_protection_enabled: Optional[StrictBool] = None
    waf_enabled: Optional[StrictBool] = None
    debug_rules: Optional[StrictBool] = None
    domains: Optional[conlist(StrictInt)] = None
    __properties = ["id", "name", "is_active", "last_editor", "last_modified", "edge_functions_enabled", "network_protection_enabled", "waf_enabled", "debug_rules", "domains"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EdgeFirewall:
        """Create an instance of EdgeFirewall from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EdgeFirewall:
        """Create an instance of EdgeFirewall from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EdgeFirewall.parse_obj(obj)

        _obj = EdgeFirewall.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "is_active": obj.get("is_active"),
            "last_editor": obj.get("last_editor"),
            "last_modified": obj.get("last_modified"),
            "edge_functions_enabled": obj.get("edge_functions_enabled"),
            "network_protection_enabled": obj.get("network_protection_enabled"),
            "waf_enabled": obj.get("waf_enabled"),
            "debug_rules": obj.get("debug_rules"),
            "domains": obj.get("domains")
        })
        return _obj


