# coding: utf-8

"""
    Edge Firewall API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt, StrictStr, validator

class NullArgumentBehavior(BaseModel):
    """
    NullArgumentBehavior
    """
    name: Optional[StrictStr] = None
    argument: Optional[StrictInt] = None
    __properties = ["name", "argument"]

    @validator('name')
    def name_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('deny', 'drop'):
            raise ValueError("must be one of enum values ('deny', 'drop')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> NullArgumentBehavior:
        """Create an instance of NullArgumentBehavior from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if argument (nullable) is None
        # and __fields_set__ contains the field
        if self.argument is None and "argument" in self.__fields_set__:
            _dict['argument'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> NullArgumentBehavior:
        """Create an instance of NullArgumentBehavior from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return NullArgumentBehavior.parse_obj(obj)

        _obj = NullArgumentBehavior.parse_obj({
            "name": obj.get("name"),
            "argument": obj.get("argument")
        })
        return _obj


