# coding: utf-8

"""
    Azion API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 3.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import networklist
from networklist.model.update_network_lists_request import UpdateNetworkListsRequest
from networklist import configuration


class TestUpdateNetworkListsRequest(unittest.TestCase):
    """UpdateNetworkListsRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
