# coding: utf-8

# flake8: noqa
"""
    Web Application Firewall API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from waf.models.create_new_waf_ruleset_request import CreateNewWAFRulesetRequest
from waf.models.links import Links
from waf.models.single_waf import SingleWAF
from waf.models.waf_domains200 import WAFDomains200
from waf.models.waf_events200 import WAFEvents200
from waf.models.waf_events400 import WAFEvents400
from waf.models.waf_events401 import WAFEvents401
from waf.models.waf_events404 import WAFEvents404
from waf.models.waf_list200 import WAFList200
from waf.models.waf_sensitivity_choices import WAFSensitivityChoices
from waf.models.waf_single200 import WAFSingle200
