# coding: utf-8

"""
    Web Application Firewall API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, conlist, validator
from waf.models.waf_sensitivity_choices import WAFSensitivityChoices

class SingleWAF(BaseModel):
    """
    SingleWAF
    """
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = Field(None, description="Identification name for WAF Rule Set.")
    mode: Optional[StrictStr] = None
    active: Optional[StrictBool] = None
    sql_injection: Optional[StrictBool] = None
    sql_injection_sensitivity: Optional[WAFSensitivityChoices] = None
    remote_file_inclusion: Optional[StrictBool] = None
    remote_file_inclusion_sensitivity: Optional[WAFSensitivityChoices] = None
    directory_traversal: Optional[StrictBool] = None
    directory_traversal_sensitivity: Optional[WAFSensitivityChoices] = None
    cross_site_scripting: Optional[StrictBool] = None
    cross_site_scripting_sensitivity: Optional[WAFSensitivityChoices] = None
    evading_tricks: Optional[StrictBool] = None
    evading_tricks_sensitivity: Optional[WAFSensitivityChoices] = None
    file_upload: Optional[StrictBool] = None
    file_upload_sensitivity: Optional[WAFSensitivityChoices] = None
    unwanted_access: Optional[StrictBool] = None
    unwanted_access_sensitivity: Optional[WAFSensitivityChoices] = None
    identified_attack: Optional[StrictBool] = None
    identified_attack_sensitivity: Optional[WAFSensitivityChoices] = None
    bypass_addresses: Optional[conlist(StrictStr)] = None
    __properties = ["id", "name", "mode", "active", "sql_injection", "sql_injection_sensitivity", "remote_file_inclusion", "remote_file_inclusion_sensitivity", "directory_traversal", "directory_traversal_sensitivity", "cross_site_scripting", "cross_site_scripting_sensitivity", "evading_tricks", "evading_tricks_sensitivity", "file_upload", "file_upload_sensitivity", "unwanted_access", "unwanted_access_sensitivity", "identified_attack", "identified_attack_sensitivity", "bypass_addresses"]

    @validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('blocking', 'counting'):
            raise ValueError("must be one of enum values ('blocking', 'counting')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SingleWAF:
        """Create an instance of SingleWAF from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SingleWAF:
        """Create an instance of SingleWAF from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SingleWAF.parse_obj(obj)

        _obj = SingleWAF.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "mode": obj.get("mode"),
            "active": obj.get("active"),
            "sql_injection": obj.get("sql_injection"),
            "sql_injection_sensitivity": obj.get("sql_injection_sensitivity"),
            "remote_file_inclusion": obj.get("remote_file_inclusion"),
            "remote_file_inclusion_sensitivity": obj.get("remote_file_inclusion_sensitivity"),
            "directory_traversal": obj.get("directory_traversal"),
            "directory_traversal_sensitivity": obj.get("directory_traversal_sensitivity"),
            "cross_site_scripting": obj.get("cross_site_scripting"),
            "cross_site_scripting_sensitivity": obj.get("cross_site_scripting_sensitivity"),
            "evading_tricks": obj.get("evading_tricks"),
            "evading_tricks_sensitivity": obj.get("evading_tricks_sensitivity"),
            "file_upload": obj.get("file_upload"),
            "file_upload_sensitivity": obj.get("file_upload_sensitivity"),
            "unwanted_access": obj.get("unwanted_access"),
            "unwanted_access_sensitivity": obj.get("unwanted_access_sensitivity"),
            "identified_attack": obj.get("identified_attack"),
            "identified_attack_sensitivity": obj.get("identified_attack_sensitivity"),
            "bypass_addresses": obj.get("bypass_addresses")
        })
        return _obj


