# flake8: noqa

# import apis into api package
from edgeapplications.api.edge_applications_cache_settings_api import EdgeApplicationsCacheSettingsApi
from edgeapplications.api.edge_applications_device_groups_api import EdgeApplicationsDeviceGroupsApi
from edgeapplications.api.edge_applications_edge_functions_instances_api import EdgeApplicationsEdgeFunctionsInstancesApi
from edgeapplications.api.edge_applications_main_settings_api import EdgeApplicationsMainSettingsApi
from edgeapplications.api.edge_applications_origins_api import EdgeApplicationsOriginsApi
from edgeapplications.api.edge_applications_rules_engine_api import EdgeApplicationsRulesEngineApi

