# coding: utf-8

"""
    Intelligent DNS

    Azion Intelligent DNS API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""

from idns.paths.intelligent_dns_zone_id_dnssec.get import GetZoneDnsSec
from idns.paths.intelligent_dns_zone_id_dnssec.patch import PutZoneDnsSec


class DNSSECApi(
    GetZoneDnsSec,
    PutZoneDnsSec,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
