# coding: utf-8

"""
    Network Lists API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, StrictStr, conlist, validator

class CreateNetworkListsRequest(BaseModel):
    """
    CreateNetworkListsRequest
    """
    name: Optional[StrictStr] = None
    items_values: Optional[conlist(StrictStr)] = None
    list_type: Optional[StrictStr] = None
    __properties = ["name", "items_values", "list_type"]

    @validator('list_type')
    def list_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('ip_cidr', 'asn', 'countries'):
            raise ValueError("must be one of enum values ('ip_cidr', 'asn', 'countries')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateNetworkListsRequest:
        """Create an instance of CreateNetworkListsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateNetworkListsRequest:
        """Create an instance of CreateNetworkListsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateNetworkListsRequest.parse_obj(obj)

        _obj = CreateNetworkListsRequest.parse_obj({
            "name": obj.get("name"),
            "items_values": obj.get("items_values"),
            "list_type": obj.get("list_type")
        })
        return _obj


