# coding: utf-8

"""
    Object Storage

    REST API OpenAPI documentation for the Object Storage

    The version of the OpenAPI document: 1.0.0 (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from storage.models.patched_bucket import PatchedBucket

class TestPatchedBucket(unittest.TestCase):
    """PatchedBucket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatchedBucket:
        """Test PatchedBucket
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatchedBucket`
        """
        model = PatchedBucket()
        if include_optional:
            return PatchedBucket(
                name = '012345',
                edge_access = 'read_only'
            )
        else:
            return PatchedBucket(
        )
        """

    def testPatchedBucket(self):
        """Test PatchedBucket"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
