# coding: utf-8

"""
    Object Storage

    REST API OpenAPI documentation for the Object Storage

    The version of the OpenAPI document: 1.0.0 (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from storage.models.edge_access_enum import EdgeAccessEnum

class TestEdgeAccessEnum(unittest.TestCase):
    """EdgeAccessEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEdgeAccessEnum(self):
        """Test EdgeAccessEnum"""
        # inst = EdgeAccessEnum()

if __name__ == '__main__':
    unittest.main()
