# coding: utf-8

"""
    Object Storage

    REST API OpenAPI documentation for the Object Storage

    The version of the OpenAPI document: 1.0.0 (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from storage.models.response_delete_bucket import ResponseDeleteBucket

class TestResponseDeleteBucket(unittest.TestCase):
    """ResponseDeleteBucket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseDeleteBucket:
        """Test ResponseDeleteBucket
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseDeleteBucket`
        """
        model = ResponseDeleteBucket()
        if include_optional:
            return ResponseDeleteBucket(
                state = 'pending',
                data = storage.models.response_delete_bucket_data.ResponseDeleteBucket_data()
            )
        else:
            return ResponseDeleteBucket(
                state = 'pending',
                data = storage.models.response_delete_bucket_data.ResponseDeleteBucket_data(),
        )
        """

    def testResponseDeleteBucket(self):
        """Test ResponseDeleteBucket"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
