# coding: utf-8

"""
    Network Lists API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

from networklist.paths.network_lists.get import NetworkListsGet
from networklist.paths.network_lists.post import NetworkListsPost
from networklist.paths.network_lists_uuid.delete import NetworkListsUuidDelete
from networklist.paths.network_lists_uuid.get import NetworkListsUuidGet
from networklist.paths.network_lists_uuid.put import NetworkListsUuidPut


class DefaultApi(
    NetworkListsGet,
    NetworkListsPost,
    NetworkListsUuidDelete,
    NetworkListsUuidGet,
    NetworkListsUuidPut,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
