# coding: utf-8

"""
    Credentials API

    Azion Orchestration  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import credentials
from credentials.model.update_credential_request import UpdateCredentialRequest
from credentials import configuration


class TestUpdateCredentialRequest(unittest.TestCase):
    """UpdateCredentialRequest unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
