# coding: utf-8

"""
    Edgenode API

    Azion Orchestration  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import edgenode
from edgenode.model.authorize_edge_nodes_response import AuthorizeEdgeNodesResponse
from edgenode import configuration


class TestAuthorizeEdgeNodesResponse(unittest.TestCase):
    """AuthorizeEdgeNodesResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
