# coding: utf-8

"""
    Edgenode API

    Azion Orchestration  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import edgenode
from edgenode.model.service_bind_detail_response import ServiceBindDetailResponse
from edgenode import configuration


class TestServiceBindDetailResponse(unittest.TestCase):
    """ServiceBindDetailResponse unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
