# coding: utf-8

"""
    Object Storage

    REST API OpenAPI documentation for the Object Storage

    The version of the OpenAPI document: 1.0.0 (v1)
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class StateEnum(str, Enum):
    """
    StateEnum
    """

    """
    allowed enum values
    """
    PENDING = 'pending'
    EXECUTED = 'executed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StateEnum from a JSON string"""
        return cls(json.loads(json_str))


