# coding: utf-8

"""
    Edge Application API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class DeviceGroupsResponseLinks(BaseModel):
    """
    DeviceGroupsResponseLinks
    """
    previous: Optional[StrictStr] = None
    next: Optional[StrictStr] = None
    __properties = ["previous", "next"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DeviceGroupsResponseLinks:
        """Create an instance of DeviceGroupsResponseLinks from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if previous (nullable) is None
        # and __fields_set__ contains the field
        if self.previous is None and "previous" in self.__fields_set__:
            _dict['previous'] = None

        # set to None if next (nullable) is None
        # and __fields_set__ contains the field
        if self.next is None and "next" in self.__fields_set__:
            _dict['next'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DeviceGroupsResponseLinks:
        """Create an instance of DeviceGroupsResponseLinks from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DeviceGroupsResponseLinks.parse_obj(obj)

        _obj = DeviceGroupsResponseLinks.parse_obj({
            "previous": obj.get("previous"),
            "next": obj.get("next")
        })
        return _obj


