# coding: utf-8

"""
    Intelligent DNS

    Azion Intelligent DNS API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import idns
from idns.model.dns_sec_delegation_signer_digest_type import DnsSecDelegationSignerDigestType
from idns import configuration


class TestDnsSecDelegationSignerDigestType(unittest.TestCase):
    """DnsSecDelegationSignerDigestType unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
