# coding: utf-8

"""
    Web Application Firewall API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Generated by: https://openapi-generator.tech
"""

from waf.paths.waf_waf_id_domains.get import GetWafDomains
from waf.paths.waf_waf_id_waf_events.get import GetWafEvents


class WAFApi(
    GetWafDomains,
    GetWafEvents,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
